language: python
python:
  - '2.7'
env:
  - SECRET_KEY=NOT_SO_SECRET APP_SETTINGS=app.config.TestingConfig CHROME_BIN=chromium-browser DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - bower install
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt --upgrade
  - gem install coveralls-lcov

script:
  - rm -rf .coverage
  - make test
  - ./node_modules/karma/bin/karma start --single-run

after_success:
  - coveralls-lcov -v -n .k_coverage/lcov.info > coverage.json
  - coveralls --merge=coverage.json
