language: python
python:
  - '2.7'
env:
  - SECRET_KEY=NOT_SO_SECRET APP_SETTINGS=app.config.TestingConfig PIVOTAL_TOKEN=TOKEN-PIVOTAL CHROME_BIN=chromium-browser DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt --upgrade
script:
  - rm -rf .coverage
  - make test
after_success:
  - coveralls
