language: python
python:
  - '2.7'
env:
  - SECRET_KEY=NOT_SO_SECRET APP_SETTINGS=app.config.TestingConfig

install:
  - sudo apt-get install phantomjs
  - npm install karma karma-coverage karma-ng-html2js-preprocessor karma-jasmine jasmine-fixture jasmine-core phantomjs karma-phantomjs-launcher
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt --upgrade

script:
  - rm -rf .coverage
  - make test
  - ./node_modules/karma/bin/karma start --browsers PhantomJS --single-run

after_success:
  - coveralls
