"""empty message

Revision ID: 29242dfbe9d2
Revises: 52d9ae15c6a9
Create Date: 2016-05-01 14:30:26.366480

"""

# revision identifiers, used by Alembic.
revision = '29242dfbe9d2'
down_revision = '52d9ae15c6a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
